- max_log_lines: 100
  max_cache_items: 5000
  max_interval: 300
  download_dir: ../../anime
  aria2: http://127.0.0.1:6800/rpc
  proxies_en: true
  proxies_url: http://localhost:7890
  error_en: true
  sources:
    dmhy:
    - https://dmhy.org/topics/list/page/{}
    - 50
    nyaa:
    - https://nyaa.si/?p={}
    - 0
    dmhy2:
    - https://dongmanhuayuan.myheartsite.com/api/acg/search
    - 0
  title:
    epsodes: (?<=[\WAE])\d\d(?=[\Wv])|(?<=第)\d\d(?=[话話])
    must:
    - 動畫
    - 简|CHS|GB|繁|CHT|BIG5
    score:
    - 简|CHS|GB
    - 1080|2160
    - 无修正
    - 无修正
    select: 0
- filters: 葬送的芙莉莲|Sousou no Frieren
  epsodes: 23+
- filters: 香格里拉|Shangri-La Frontier
  epsodes: 19+
- filters: 不死不幸|Undead Unluck
  epsodes: 19+
- filters: 迷宫饭|Dungeon Meshi
  epsodes: 7+
- filters: 成为魔法少女|Mahou Shoujo ni Akogarete
  epsodes: 7+
- filters: 月光下的异世界之旅|Tsuki ga Michibiku Isekai Douchuu
  epsodes: 7+
- filters: 我心里危险的东西|Boku no Kokoro no Yabai Yatsu
  epsodes: 19-28
- filters: 我独自升级|Ore Dake Level Up
  epsodes: 7+
  title:
    epsodes: (?<=[\WAE])\d+(?=[\Wv])|(?<=第)\d+(?=[话話])
    must:
    - 動畫
    - 简|CHS|GB|繁|CHT|BIG5
    score:
    - 简|CHS|GB
    - 1080|2160
    - 无修正
    - 无修正
    select: 0
- filters: 弱角友崎
  epsodes: 7+
- filters: 异修罗|Ishura
  epsodes: 7+
- filters: 魔都精兵的奴隶|Mato Seihei no Slave
  epsodes: 7+
- filters: 狩火之王
  epsodes: 6+
- filters: 婚戒物语|Kekkon Yubiwa Monogatari|Tales of Wedding Rings
  epsodes: 7+
- filters: 秒杀外挂|Sokushi Cheat ga
  epsodes: 7+
- filters: Metallic Rouge|金属口红
  epsodes: 6+
- filters: Bang Bravern|勇气爆发
  epsodes: 6+
